[2025-01-21T19:34:15.442+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-21T19:34:15.519+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_data_drift_notify_retrain.detect_data_drift_task manual__2025-01-21T19:26:38.017295+00:00 [queued]>
[2025-01-21T19:34:15.541+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_data_drift_notify_retrain.detect_data_drift_task manual__2025-01-21T19:26:38.017295+00:00 [queued]>
[2025-01-21T19:34:15.544+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-01-21T19:34:15.597+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): detect_data_drift_task> on 2025-01-21 19:26:38.017295+00:00
[2025-01-21T19:34:15.618+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-21T19:34:15.625+0000] {standard_task_runner.py:72} INFO - Started process 172 to run task
[2025-01-21T19:34:15.642+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'detect_data_drift_notify_retrain', 'detect_data_drift_task', 'manual__2025-01-21T19:26:38.017295+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/monitoring-dag.py', '--cfg-path', '/tmp/tmp6xrbk_bz']
[2025-01-21T19:34:15.648+0000] {standard_task_runner.py:105} INFO - Job 165: Subtask detect_data_drift_task
[2025-01-21T19:34:15.782+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_data_drift_notify_retrain.detect_data_drift_task manual__2025-01-21T19:26:38.017295+00:00 [running]> on host d3de575648b4
[2025-01-21T19:34:16.177+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='RL' AIRFLOW_CTX_DAG_ID='detect_data_drift_notify_retrain' AIRFLOW_CTX_TASK_ID='detect_data_drift_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-21T19:26:38.017295+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-21T19:26:38.017295+00:00'
[2025-01-21T19:34:16.194+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-21T19:34:16.268+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-21T19:34:16.269+0000] {monitoring-dag.py:83} INFO - Loading files from S3...
[2025-01-21T19:34:16.270+0000] {monitoring-dag.py:58} INFO - Starting to load files from S3...
[2025-01-21T19:34:16.298+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-01-21T19:34:16.516+0000] {monitoring-dag.py:62} INFO - Loading reference file: covertype-final-project-jedha/covertype/reference/covtype_80.csv
[2025-01-21T19:37:16.589+0000] {job.py:229} INFO - Heartbeat recovered after 11.52 seconds
[2025-01-21T19:37:24.361+0000] {job.py:229} INFO - Heartbeat recovered after 11.13 seconds
[2025-01-21T19:40:08.071+0000] {local_task_job_runner.py:266} INFO - Task exited with return code -9For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed
[2025-01-21T19:40:08.140+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-21T19:40:08.157+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
