[2025-01-17T18:56:41.135+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-17T18:56:41.231+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-17T18:56:22.502747+00:00 [queued]>
[2025-01-17T18:56:41.280+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-17T18:56:22.502747+00:00 [queued]>
[2025-01-17T18:56:41.286+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-01-17T18:56:41.406+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): detect_file_task> on 2025-01-17 18:56:22.502747+00:00
[2025-01-17T18:56:41.445+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=183) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-17T18:56:41.449+0000] {standard_task_runner.py:72} INFO - Started process 188 to run task
[2025-01-17T18:56:41.451+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'detect_data_drift_notify_retrain', 'detect_file_task', 'manual__2025-01-17T18:56:22.502747+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/monitoring-dag.py', '--cfg-path', '/tmp/tmpd27s67os']
[2025-01-17T18:56:41.455+0000] {standard_task_runner.py:105} INFO - Job 46: Subtask detect_file_task
[2025-01-17T18:56:41.692+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-17T18:56:22.502747+00:00 [running]> on host fb760283cf73
[2025-01-17T18:56:42.137+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='RL' AIRFLOW_CTX_DAG_ID='detect_data_drift_notify_retrain' AIRFLOW_CTX_TASK_ID='detect_file_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T18:56:22.502747+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T18:56:22.502747+00:00'
[2025-01-17T18:56:42.139+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-17T18:56:42.194+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-17T18:56:42.256+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-01-17T18:56:42.716+0000] {monitoring-dag.py:46} INFO - Checking file in S3: covertype-final-project-jedha/covertype/new_data/covtype_sample_drift.csv
[2025-01-17T18:56:50.806+0000] {monitoring-dag.py:48} INFO - File found in S3
[2025-01-17T18:56:50.815+0000] {python.py:240} INFO - Done. Returned value was: detect_data_drift_task
[2025-01-17T18:56:50.828+0000] {branch.py:38} INFO - Branch into detect_data_drift_task
[2025-01-17T18:56:50.830+0000] {skipmixin.py:230} INFO - Following branch ('detect_data_drift_task',)
[2025-01-17T18:56:50.869+0000] {skipmixin.py:278} INFO - Skipping tasks [('no_file_found_task', -1)]
[2025-01-17T18:56:51.025+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-17T18:56:51.027+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=detect_data_drift_notify_retrain, task_id=detect_file_task, run_id=manual__2025-01-17T18:56:22.502747+00:00, execution_date=20250117T185622, start_date=20250117T185641, end_date=20250117T185651
[2025-01-17T18:56:51.208+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-17T18:56:51.247+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
