[2025-01-22T00:11:56.776+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-22T00:11:56.845+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-22T00:11:46.947767+00:00 [queued]>
[2025-01-22T00:11:56.885+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-22T00:11:46.947767+00:00 [queued]>
[2025-01-22T00:11:56.886+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-01-22T00:11:56.945+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): detect_file_task> on 2025-01-22 00:11:46.947767+00:00
[2025-01-22T00:11:56.977+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=92) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-22T00:11:56.980+0000] {standard_task_runner.py:72} INFO - Started process 97 to run task
[2025-01-22T00:11:56.986+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'detect_data_drift_notify_retrain', 'detect_file_task', 'manual__2025-01-22T00:11:46.947767+00:00', '--job-id', '235', '--raw', '--subdir', 'DAGS_FOLDER/monitoring-dag.py', '--cfg-path', '/tmp/tmp91xlf5zu']
[2025-01-22T00:11:57.002+0000] {standard_task_runner.py:105} INFO - Job 235: Subtask detect_file_task
[2025-01-22T00:11:57.267+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-22T00:11:46.947767+00:00 [running]> on host d3de575648b4
[2025-01-22T00:11:57.558+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='RL' AIRFLOW_CTX_DAG_ID='detect_data_drift_notify_retrain' AIRFLOW_CTX_TASK_ID='detect_file_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:11:46.947767+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-22T00:11:46.947767+00:00'
[2025-01-22T00:11:57.566+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-22T00:11:57.613+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-22T00:11:57.689+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-01-22T00:11:58.070+0000] {monitoring-dag.py:46} INFO - Checking file in S3: covertype-final-project-jedha/covertype/new_data/covtype_sample_drift.csv
[2025-01-22T00:12:04.484+0000] {monitoring-dag.py:48} INFO - File found in S3
[2025-01-22T00:12:04.493+0000] {python.py:240} INFO - Done. Returned value was: detect_data_drift_task
[2025-01-22T00:12:04.499+0000] {branch.py:38} INFO - Branch into detect_data_drift_task
[2025-01-22T00:12:04.501+0000] {skipmixin.py:230} INFO - Following branch ('detect_data_drift_task',)
[2025-01-22T00:12:04.557+0000] {skipmixin.py:278} INFO - Skipping tasks [('no_file_found_task', -1)]
[2025-01-22T00:12:04.664+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-22T00:12:04.665+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=detect_data_drift_notify_retrain, task_id=detect_file_task, run_id=manual__2025-01-22T00:11:46.947767+00:00, execution_date=20250122T001146, start_date=20250122T001156, end_date=20250122T001204
[2025-01-22T00:12:04.781+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-22T00:12:04.915+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-22T00:12:04.924+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
