[2025-01-17T17:39:33.051+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-17T17:39:33.091+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-17T17:39:23.100117+00:00 [queued]>
[2025-01-17T17:39:33.107+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-17T17:39:23.100117+00:00 [queued]>
[2025-01-17T17:39:33.108+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-01-17T17:39:33.137+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): detect_file_task> on 2025-01-17 17:39:23.100117+00:00
[2025-01-17T17:39:33.172+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1045) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-17T17:39:33.177+0000] {standard_task_runner.py:72} INFO - Started process 1050 to run task
[2025-01-17T17:39:33.185+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'detect_data_drift_notify_retrain', 'detect_file_task', 'manual__2025-01-17T17:39:23.100117+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/monitoring-dag.py', '--cfg-path', '/tmp/tmpzgez5egq']
[2025-01-17T17:39:33.193+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask detect_file_task
[2025-01-17T17:39:33.367+0000] {task_command.py:467} INFO - Running <TaskInstance: detect_data_drift_notify_retrain.detect_file_task manual__2025-01-17T17:39:23.100117+00:00 [running]> on host f68435ca3fd9
[2025-01-17T17:39:33.851+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='RL' AIRFLOW_CTX_DAG_ID='detect_data_drift_notify_retrain' AIRFLOW_CTX_TASK_ID='detect_file_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T17:39:23.100117+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T17:39:23.100117+00:00'
[2025-01-17T17:39:33.854+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-17T17:39:33.878+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-01-17T17:39:33.926+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-01-17T17:39:34.056+0000] {monitoring-dag.py:46} INFO - Checking file in S3: covertype-final-project-jedha/covertype/new_data/covtype_sample_drift.csv
[2025-01-17T17:39:42.755+0000] {monitoring-dag.py:48} INFO - File found in S3
[2025-01-17T17:39:42.761+0000] {python.py:240} INFO - Done. Returned value was: detect_data_drift_task
[2025-01-17T17:39:42.764+0000] {branch.py:38} INFO - Branch into detect_data_drift_task
[2025-01-17T17:39:42.767+0000] {skipmixin.py:230} INFO - Following branch ('detect_data_drift_task',)
[2025-01-17T17:39:42.796+0000] {skipmixin.py:278} INFO - Skipping tasks [('no_file_found_task', -1)]
[2025-01-17T17:39:42.910+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-17T17:39:42.912+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=detect_data_drift_notify_retrain, task_id=detect_file_task, run_id=manual__2025-01-17T17:39:23.100117+00:00, execution_date=20250117T173923, start_date=20250117T173933, end_date=20250117T173942
[2025-01-17T17:39:42.993+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-17T17:39:43.103+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-17T17:39:43.110+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
